---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: testvol1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.0.1.1
    path: '/xfer'

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi